// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkK6OlUe5G_XtfOVM0kK1O8Yg-IQ3se3g',
    appId: '1:840114735417:web:83288f8c1b09c2522100e8',
    messagingSenderId: '840114735417',
    projectId: 'appqlcv-34619',
    authDomain: 'appqlcv-34619.firebaseapp.com',
    databaseURL: 'https://appqlcv-34619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appqlcv-34619.firebasestorage.app',
    measurementId: 'G-7249DNG013',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcF4sICuZYMhuJFSrX1Fxb2YbOKRjjZQ',
    appId: '1:840114735417:android:3a2d9f92b3b764d42100e8',
    messagingSenderId: '840114735417',
    projectId: 'appqlcv-34619',
    databaseURL: 'https://appqlcv-34619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appqlcv-34619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV0AEtftGucFIvBfPxxVa5qztUQldyBrk',
    appId: '1:840114735417:ios:4a3a6f7b00c07c8b2100e8',
    messagingSenderId: '840114735417',
    projectId: 'appqlcv-34619',
    databaseURL: 'https://appqlcv-34619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appqlcv-34619.firebasestorage.app',
    iosBundleId: 'com.example.appqlcv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV0AEtftGucFIvBfPxxVa5qztUQldyBrk',
    appId: '1:840114735417:ios:4a3a6f7b00c07c8b2100e8',
    messagingSenderId: '840114735417',
    projectId: 'appqlcv-34619',
    databaseURL: 'https://appqlcv-34619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appqlcv-34619.firebasestorage.app',
    iosBundleId: 'com.example.appqlcv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkK6OlUe5G_XtfOVM0kK1O8Yg-IQ3se3g',
    appId: '1:840114735417:web:64b72dda6f91c5a22100e8',
    messagingSenderId: '840114735417',
    projectId: 'appqlcv-34619',
    authDomain: 'appqlcv-34619.firebaseapp.com',
    databaseURL: 'https://appqlcv-34619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appqlcv-34619.firebasestorage.app',
    measurementId: 'G-V10EQ1YYW7',
  );
}
